Repository elementary/switchboard-plug-onlineaccounts, pull requests merged in 2021-09, with the labels that each got.

#219 Fixes #210: Close dialog on ESC key release
  src/Dialogs/CaldavDialog.vala
  src/Dialogs/Imap/ImapDialog.vala
Labels: Bitesize, Enhancement

#218 Ignore Calendar Subscriptions
  src/Dialogs/CaldavDialog.vala
Labels: Bitesize, Bug

#222 Set refresh interval for IMAP
  data/onlineaccounts.appdata.xml.in
  src/Dialogs/Imap/ImapDialog.vala
Labels: Bitesize, Enhancement

#231 Release 6.2.1
  data/onlineaccounts.appdata.xml.in
  meson.build
Labels: Release
